// Code generated by MockGen. DO NOT EDIT.
// Source: symbols.go

// Package repo_mocks is a generated GoMock package.
package repo_mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/linnoxlewis/trade-bot/internal/domain"
)

// MockSymbolRepo is a mock of SymbolRepo interface.
type MockSymbolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSymbolRepoMockRecorder
}

// MockSymbolRepoMockRecorder is the mock recorder for MockSymbolRepo.
type MockSymbolRepoMockRecorder struct {
	mock *MockSymbolRepo
}

// NewMockSymbolRepo creates a new mock instance.
func NewMockSymbolRepo(ctrl *gomock.Controller) *MockSymbolRepo {
	mock := &MockSymbolRepo{ctrl: ctrl}
	mock.recorder = &MockSymbolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSymbolRepo) EXPECT() *MockSymbolRepoMockRecorder {
	return m.recorder
}

// AddSymbol mocks base method.
func (m *MockSymbolRepo) AddSymbol(ctx context.Context, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSymbol", ctx, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSymbol indicates an expected call of AddSymbol.
func (mr *MockSymbolRepoMockRecorder) AddSymbol(ctx, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSymbol", reflect.TypeOf((*MockSymbolRepo)(nil).AddSymbol), ctx, symbol)
}

// GetDefaultSymbols mocks base method.
func (m *MockSymbolRepo) GetDefaultSymbols(ctx context.Context) (domain.SymbolList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultSymbols", ctx)
	ret0, _ := ret[0].(domain.SymbolList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultSymbols indicates an expected call of GetDefaultSymbols.
func (mr *MockSymbolRepoMockRecorder) GetDefaultSymbols(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultSymbols", reflect.TypeOf((*MockSymbolRepo)(nil).GetDefaultSymbols), ctx)
}
